services:

  postgres:
    image: postgres:17

    container_name: dcc-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: dcc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  dcc:
    build:
      context: .
      dockerfile: app/Dockerfile

    container_name: dcc

    restart: unless-stopped

    depends_on:
      - postgres

    env_file:
      - .env

    ports:
      - "8000:8000"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Krishna@123
      POSTGRES_DB: dcc
volumes:
  postgres_data: